---
name: New task
description: Create a new task to manage a piece of work
title: '[Task]: '

body:
  - type: markdown
    attributes:
      value: "## Creating a task"
  - type: markdown
    attributes:
      value: |
        This form should be used by members of the cybersecurity team only, to create new tasks to represent some work. Most tasks should be assigned to a milestone. If you would like to request some work to be done please fill out the work requst form.

  - type: textarea
    id: description
    attributes:
      label: Task description
      description: Briefly describe the work to be done.
    validations:
      required: true
      
  - type: textarea
    id: requirements
    attributes:
      label: Requirements
      description: List the specific requirements or sub tasks for this item.
    validations:
      required: true
      
  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance criteria
      description: The definition of done.
    validations:
      required: true
      
  - type: checkboxes
    id: checklist
    attributes:
      label: Creation checklist
      description: "Before submitting this task please ensure you have done the following:"
      options:
        - label: I have assigned this task to the correct people
          required: false
        - label: I have added the most appropriate labels
          required: true
        - label: I have linked the correct milestone and/or project
          required: true
          
